/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeviceTypesIndexRouteImport } from './routes/device-types.index'
import { Route as DevicesIndexRouteImport } from './routes/devices.index'
import { Route as DevicesSerialRouteImport } from './routes/devices.$serial'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceTypesIndexRoute = DeviceTypesIndexRouteImport.update({
  id: '/device-types/',
  path: '/device-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesSerialRoute = DevicesSerialRouteImport.update({
  id: '/devices/$serial',
  path: '/devices/$serial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/devices/$serial': typeof DevicesSerialRoute
  '/device-types/': typeof DeviceTypesIndexRoute
  '/devices/': typeof DevicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/devices/$serial': typeof DevicesSerialRoute
  '/device-types': typeof DeviceTypesIndexRoute
  '/devices': typeof DevicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/devices/$serial': typeof DevicesSerialRoute
  '/device-types/': typeof DeviceTypesIndexRoute
  '/devices/': typeof DevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/devices/$serial' | '/device-types/' | '/devices/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/devices/$serial' | '/device-types' | '/devices'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/devices/$serial'
    | '/device-types/'
    | '/devices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DevicesSerialRoute: typeof DevicesSerialRoute
  DeviceTypesIndexRoute: typeof DeviceTypesIndexRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-types/': {
      id: '/device-types/'
      path: '/device-types'
      fullPath: '/device-types/'
      preLoaderRoute: typeof DeviceTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/': {
      id: '/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$serial': {
      id: '/devices/$serial'
      path: '/devices/$serial'
      fullPath: '/devices/$serial'
      preLoaderRoute: typeof DevicesSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DevicesSerialRoute: DevicesSerialRoute,
  DeviceTypesIndexRoute: DeviceTypesIndexRoute,
  DevicesIndexRoute: DevicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
